"""
app_icon.py -- the PrimeAtlas globe icon (primeatlas/core/assets/, generated by
installer/make_icons.py) for every window the app opens, plus the process-level
AppUserModelID that makes the Windows taskbar actually show it.

The app runs as pythonw.exe: without an explicit AppUserModelID, Windows groups its windows
under Python and shows Python's icon on the taskbar regardless of the window's own icon.
The installer's shortcuts carry the same ID (installer/PrimeAtlasSetup.iss), so a pinned
shortcut and the running window share one taskbar button. The ring_viz renderer is a
separate process and sets the ID itself (gl_setup.py).

Every function here is best-effort and never raises -- an icon is never worth a crash.
Pure Python, no Pillow: GLFW gets raw RGBA files, Tk gets the .ico (or the PNG, which Tk
8.6 reads natively).
"""
import os

ASSETS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "assets")
ICO_PATH = os.path.join(ASSETS_DIR, "primeatlas.ico")
PNG_PATH = os.path.join(ASSETS_DIR, "primeatlas_256.png")
GLFW_ICON_SIZES = (16, 32, 48)
APP_USER_MODEL_ID = "Flaman55.PrimeAtlas"


def rgba_path(size, assets_dir=ASSETS_DIR):
    return os.path.join(assets_dir, f"primeatlas_{size}.rgba")


def set_app_user_model_id(shell32=None, os_name=os.name):
    """Call before the first window is created. True on success."""
    if os_name != "nt":
        return False
    try:
        if shell32 is None:
            import ctypes
            shell32 = ctypes.windll.shell32
        shell32.SetCurrentProcessExplicitAppUserModelID(APP_USER_MODEL_ID)
        return True
    except Exception:
        return False


def apply_tk_icon(root, os_name=os.name, photo_factory=None):
    """Sets the icon on a Tk root. On Windows iconbitmap(default=...) also applies to every
    Toplevel created later; elsewhere (or if that fails) iconphoto with the PNG."""
    if os_name == "nt":
        try:
            root.iconbitmap(default=ICO_PATH)
            return True
        except Exception:
            pass
    try:
        if photo_factory is None:
            import tkinter
            photo_factory = tkinter.PhotoImage
        image = photo_factory(file=PNG_PATH)
        root.iconphoto(True, image)
        root._primeatlas_icon_ref = image  # keep the PhotoImage alive
        return True
    except Exception:
        return False


def glfw_icon_images(assets_dir=ASSETS_DIR):
    """[(width, height, pixels[row][col] -> RGBA bytes), ...] -- the nested-sequence form
    pyGLFW's set_window_icon() accepts without Pillow. [] if the assets are missing."""
    images = []
    for size in GLFW_ICON_SIZES:
        try:
            with open(rgba_path(size, assets_dir), "rb") as f:
                raw = f.read()
        except OSError:
            continue
        if len(raw) != size * size * 4:
            continue
        rows = [[raw[(r * size + c) * 4:(r * size + c) * 4 + 4] for c in range(size)]
                for r in range(size)]
        images.append((size, size, rows))
    return images
